apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-ops-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing-ops-dev
  template:
    metadata:
      labels:
        app: testing-ops-dev
    spec:
      containers:
      - name: testing-ops
        image: docker.io/ahmadmajdi96/testing-ops:6b59cdc029087d2e105a1c7c0d0d38db36a1b100
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
