apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-ops
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing-ops
  template:
    metadata:
      labels:
        app: testing-ops
    spec:
      containers:
      - name: testing-ops
        image: docker.io/ahmadmajdi96/testing-ops:0c6f7dacdc068959304804ce6c1f1eab7b003989
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
