apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing_ops-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmadmajdi96/gitops-configs.git
    targetRevision: main
    path: dev/testing_ops
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true